POST https://capstone-deploy-production.up.railway.app/add-project
Content-Type: application/json

{
"project_code": "test20",
"title": "Grow a Tree 2",
"description": "The 'Grow a Tree' citizen science app empowers students to participate in tree-planting and growth tracking projects while contributing valuable data for environmental research. Students can record observations such as tree height, leaf color, and local weather conditions, fostering both scientific engagement and ecological awareness.",
"instructions": "Log in using your assigned project code and begin documenting observations about your assigned tree. Take photos, measure growth metrics, and input data into the app regularly."
}