POST https://capstone-deploy-production.up.railway.app/add-project
Content-Type: application/json

{
"project_code": "NIA93J",
"title": "Test Project Steve",
"description": "Test Project Steve",
"instructions": "Test Instructions Steve"
}