GET https://capstone-deploy-production.up.railway.app/project/1234567
Cookie: session=.eJwdzjEOwzAIQNG7eO4ABgzkMpFtsNo1aaaqd2_U_evrfcq-jjyfZXsfVz7K_oqyFVxp4O48XUk6KPvwjo1tRAgzTwZcQ8yDsgFFdWgrCBjVW_PUMDNNEms0-h0KSjKOrAAwq1bts97jtbiykuNUp8UoI5v3LDfkOvP4a-z7A8SkLUI.Zz__cA.Ejwjb7ByUT9tkFNeUP09b7NG_lk